# Generated by Django 5.2.7 on 2025-10-27 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(blank=True, choices=[('Groceries', 'Groceries'), ('Rent', 'Rent'), ('Utilities', 'Utilities'), ('Subscriptions', 'Subscriptions'), ('Restaurants', 'Restaurants'), ('Transportation', 'Transportation'), ('Shopping', 'Shopping'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
