# Generated by Django 5.2.8 on 2025-11-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_category_alter_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='budget_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
